let locationsData = [
    {
        date: "2025-10-20",
        location: "關西國際機場 (Kansai Intl. Airport)",
        category: "transport",
        coordinates: [34.4343, 135.2444],
        description: "抵達關西，搭乘南海電鐵前往難波。",
        image: "",
    },
    {
        date: "2025-10-20",
        location: "南海難波車站 (Nankai Namba Station)",
        category: "transport",
        coordinates: [34.661, 135.5015],
        description: "抵達大阪南區的交通樞紐。",
        image: "",
    },
    {
        date: "2025-10-20",
        location: "美津の (Mizuno Okonomiyaki)",
        category: "food",
        coordinates: [34.6686, 135.5028],
        description: "午餐品嚐米其林推薦的道地大阪燒。",
        image: "",
    },
    {
        date: "2025-10-20",
        location: "黑門市場 (Kuromon Market)",
        category: "sight",
        coordinates: [34.6659, 135.5065],
        description: "被稱為大阪的廚房，感受市場活力。",
        image: "",
    },
    {
        date: "2025-10-20",
        location: "法善寺橫丁 (Hozenji Yokocho)",
        category: "sight",
        coordinates: [34.668, 135.503],
        description: "充滿江戶風情的石板小巷，非常寧靜。",
        image: "",
    },
    {
        date: "2025-10-20",
        location: "通天閣 (Tsutenkaku Tower)",
        category: "sight",
        coordinates: [34.6525, 135.5063],
        description: "前往新世界地區，登上大阪的經典地標。",
        image: "",
    },
    {
        date: "2025-10-20",
        location: "元祖串炸 (Kushikatsu Daruma)",
        category: "food",
        coordinates: [34.652, 135.506],
        description: "晚餐品嚐新世界名物「炸串」，醬汁禁止沾第二次！",
        image: "",
    },
    {
        date: "2025-10-20",
        location: "Hotel Royal Classic Osaka",
        category: "stay",
        coordinates: [34.6635, 135.5018],
        description: "入住由建築師隈研吾設計的飯店，位於難波車站上方。",
        image: "",
    },
    {
        date: "2025-10-21",
        location: "Hotel Royal Classic Osaka",
        category: "stay",
        coordinates: [34.6635, 135.5018],
        description: "從飯店出發，開始第二天的大阪深度之旅。",
        image: "",
    },
    {
        date: "2025-10-21",
        location: "四天王寺 (Shitennoji Temple)",
        category: "sight",
        coordinates: [34.6558, 135.517],
        description: "參拜日本最古老的官家佛寺之一。",
        image: "",
    },
    {
        date: "2025-10-21",
        location: "大阪城天守閣 (Osaka Castle)",
        category: "sight",
        coordinates: [34.6873, 135.5262],
        description: "參觀大阪的歷史象徵，了解豐臣秀吉的故事。",
        image: "",
    },
    {
        date: "2025-10-21",
        location: "JO-TERRACE OSAKA",
        category: "food",
        coordinates: [34.6888, 135.53],
        description: "午餐在大阪城公園旁的複合設施用餐。",
        image: "",
    },
    {
        date: "2025-10-21",
        location: "JR大阪車站 (JR Osaka Station)",
        category: "transport",
        coordinates: [34.7025, 135.496],
        description: "領取行李後，從這裡搭乘新快速列車前往京都。",
        image: "",
    },
    {
        date: "2025-10-21",
        location: "京都祇園賽萊斯廷飯店 (The Celestine Kyoto Gion)",
        category: "stay",
        coordinates: [34.9978, 135.7778],
        description: "抵達京都，入住位於祇園的飯店，交通便利且氛圍佳。",
        image: "",
    },
    {
        date: "2025-10-21",
        location: "祇園花見小路 (Gion Hanamikoji)",
        category: "sight",
        coordinates: [35.0028, 135.7744],
        description: "晚上輕裝出發，夜遊祇園，感受古都的夜晚魅力。",
        image: "",
    },
    {
        date: "2025-10-21",
        location: "葱や平吉 先斗町店",
        category: "food",
        coordinates: [35.0065, 135.7708],
        description: "晚餐在充滿風情的先斗町品嚐以蔥為主題的特色料理。",
        image: "",
    },
    {
        date: "2025-10-22",
        location: "京都祇園賽萊斯廷飯店 (The Celestine Kyoto Gion)",
        category: "stay",
        coordinates: [34.9978, 135.7778],
        description: "在京都的早晨，準備出發進行東山區經典路線之旅。",
        image: "",
    },
    {
        date: "2025-10-22",
        location: "清水寺 (Kiyomizu-dera Temple)",
        category: "sight",
        coordinates: [34.9949, 135.7851],
        description: "從飯店搭乘巴士，參觀京都最經典的世界遺產。",
        image: "",
    },
    {
        date: "2025-10-22",
        location: "二年坂 & 三年坂 (Ninenzaka & Sannenzaka)",
        category: "sight",
        coordinates: [34.9975, 135.782],
        description: "走在充滿古都風情的石板路上。",
        image: "",
    },
    {
        date: "2025-10-22",
        location: "ひさご (Hisago Oyakodon)",
        category: "food",
        coordinates: [35.001, 135.7788],
        description: "午餐品嚐祇園附近知名的美味親子丼。",
        image: "",
    },
    {
        date: "2025-10-22",
        location: "JR稻荷車站 (JR Inari Station)",
        category: "transport",
        coordinates: [34.9675, 135.7725],
        description: "搭乘電車，準備前往伏見稻荷大社。",
        image: "",
    },
    {
        date: "2025-10-22",
        location: "伏見稻荷大社 (Fushimi Inari Shrine)",
        category: "sight",
        coordinates: [34.9671, 135.7727],
        description: "穿梭在聞名於世的千本鳥居中。",
        image: "",
    },
    {
        date: "2025-10-22",
        location: "豬一 (Inoichi Ramen)",
        category: "food",
        coordinates: [35.0005, 135.7675],
        description: "晚餐品嚐米其林必比登推薦的京都醬油拉麵。",
        image: "",
    },
    {
        date: "2025-10-22",
        location: "京都祇園賽萊斯廷飯店 (The Celestine Kyoto Gion)",
        category: "stay",
        coordinates: [34.9978, 135.7778],
        description: "在京都的第二晚住宿。",
        image: "",
    },
    {
        date: "2025-10-23",
        location: "京都祇園賽萊斯廷飯店 (The Celestine Kyoto Gion)",
        category: "stay",
        coordinates: [34.9978, 135.7778],
        description: "從飯店退房，出發前往嵐山。",
        image: "",
    },
    {
        date: "2025-10-23",
        location: "JR嵯峨嵐山站 (Saga-Arashiyama Station)",
        category: "transport",
        coordinates: [35.0163, 135.6813],
        description: "搭乘JR抵達嵐山。",
        image: "",
    },
    {
        date: "2025-10-23",
        location: "嵐山竹林小徑 (Arashiyama Bamboo Grove)",
        category: "sight",
        coordinates: [35.0173, 135.6738],
        description: "漫步在靜謐的竹林隧道中。",
        image: "",
    },
    {
        date: "2025-10-23",
        location: "天龍寺 (Tenryu-ji Temple)",
        category: "sight",
        coordinates: [35.0153, 135.6743],
        description: "參觀世界遺產，曹源池庭園的景色絕美。",
        image: "",
    },
    {
        date: "2025-10-23",
        location: "嵐山よしむら (Arashiyama Yoshimura)",
        category: "food",
        coordinates: [35.013, 135.676],
        description: "午餐品嚐可以欣賞渡月橋景色的手打蕎麥麵。",
        image: "",
    },
    {
        date: "2025-10-23",
        location: "金閣寺 (Kinkaku-ji Temple)",
        category: "sight",
        coordinates: [35.0394, 135.7292],
        description: "搭乘巴士，參觀金光閃閃的舍利殿。",
        image: "",
    },
    {
        date: "2025-10-23",
        location: "JR京都車站 (JR Kyoto Station)",
        category: "transport",
        coordinates: [34.9858, 135.7588],
        description: "返回京都車站，領取行李，準備返回大阪。",
        image: "",
    },
    {
        date: "2025-10-23",
        location: "大阪希爾頓飯店 (Hilton Osaka)",
        category: "stay",
        coordinates: [34.7018, 135.495],
        description: "今晚入住梅田地區，方便明天前往機場。",
        image: "",
    },
    {
        date: "2025-10-23",
        location: "梅田藍天大廈 (Umeda Sky Building)",
        category: "sight",
        coordinates: [34.7055, 135.4903],
        description: "登上空中庭園展望台，欣賞最後一晚的大阪夜景。",
        image: "",
    },
    {
        date: "2025-10-23",
        location: "滝見小路 (Takimi Koji)",
        category: "food",
        coordinates: [34.705, 135.4905],
        description: "晚餐在藍天大廈地下的復古美食街用餐。",
        image: "",
    },
    {
        date: "2025-10-24",
        location: "大阪希爾頓飯店 (Hilton Osaka)",
        category: "stay",
        coordinates: [34.7018, 135.495],
        description: "在大阪的最後一早，從飯店出發。",
        image: "",
    },
    {
        date: "2025-10-24",
        location: "心齋橋商店街 (Shinsaibashi)",
        category: "sight",
        coordinates: [34.673, 135.5012],
        description: "進行最後的購物與採購。",
        image: "",
    },
    {
        date: "2025-10-24",
        location: "大丸心齋橋店 (Daimaru Shinsaibashi)",
        category: "food",
        coordinates: [34.6725, 135.5015],
        description: "在百貨公司的美食街享用午餐。",
        image: "",
    },
    {
        date: "2025-10-24",
        location: "大阪希爾頓飯店前 (Airport Limousine Bus Stop)",
        category: "transport",
        coordinates: [34.702, 135.4955],
        description: "從飯店前搭乘機場利木津巴士直達關西機場。",
        image: "",
    },
    {
        date: "2025-10-24",
        location: "關西國際機場 (Kansai Intl. Airport)",
        category: "transport",
        coordinates: [34.4343, 135.2444],
        description: "滿載回憶，準備回家。",
        image: "",
    },
];
