let locationsData = [
    {
        date: "2025-04-10",
        location: "Home, Sweet Home",
        category: "transport",
        coordinates: [25.033, 121.5654], // 座標為台北市
        description: "出發前往日本九州！",
        image: "",
    },
    {
        date: "2025-04-10",
        location: "福岡機場 (Fukuoka Airport)",
        category: "transport",
        coordinates: [33.5859, 130.4506],
        description: "抵達九州的門戶，準備開始旅程。",
        image: "",
    },
    {
        date: "2025-04-10",
        location: "大濠公園 (Ohori Park)",
        category: "sight",
        coordinates: [33.5853, 130.3752],
        description: "福岡市中心的都市綠洲，有著美麗的湖景。",
        image: "",
    },
    {
        date: "2025-04-10",
        location: "福岡城跡 (Fukuoka Castle Ruins)",
        category: "sight",
        coordinates: [33.5861, 130.3824],
        description: "緊鄰大濠公園，感受歷史的痕跡。",
        image: "",
    },
    {
        date: "2025-04-10",
        location: "一蘭拉麵 天神西通店",
        category: "food",
        coordinates: [33.591, 130.3988],
        description: "品嚐福岡最經典的豚骨拉麵作為午餐。",
        image: "",
    },
    {
        date: "2025-04-10",
        location: "櫛田神社 (Kushida Shrine)",
        category: "sight",
        coordinates: [33.5942, 130.4117],
        description: "博多的總鎮守，歷史悠久，氛圍莊嚴。",
        image: "",
    },
    {
        date: "2025-04-10",
        location: "運河城博多 (Canal City Hakata)",
        category: "sight",
        coordinates: [33.5898, 130.4112],
        description: "大型複合式購物中心，逛街購物的好去處。",
        image: "",
    },
    {
        date: "2025-04-10",
        location: "もつ鍋おおやま (牛雜鍋大山)",
        category: "food",
        coordinates: [33.5895, 130.3985],
        description: "晚餐享用福岡鄉土料理牛雜鍋。",
        image: "",
    },
    {
        date: "2025-04-10",
        location: "福岡日航飯店 (Hotel Nikko Fukuoka)",
        category: "stay",
        coordinates: [33.5905, 130.4208],
        description: "今晚的住宿地點，位於博多車站旁，交通便利。",
        image: "",
    },
    {
        date: "2025-04-11",
        location: "海地獄 (Umi Jigoku)",
        category: "sight",
        coordinates: [33.315, 131.47],
        description: "從福岡來到別府，參觀神秘的蔚藍色溫泉地獄。",
        image: "",
    },
    {
        date: "2025-04-11",
        location: "鬼山地獄 (Oniyama Jigoku)",
        category: "sight",
        coordinates: [33.3155, 131.4695],
        description: "又稱鱷魚地獄，可以看到許多鱷魚。",
        image: "",
    },
    {
        date: "2025-04-11",
        location: "地獄蒸工房 鐵輪",
        category: "food",
        coordinates: [33.3142, 131.4746],
        description: "午餐體驗利用溫泉蒸氣烹煮的鄉土料理。",
        image: "",
    },
    {
        date: "2025-04-11",
        location: "別府纜車 (Beppu Ropeway)",
        category: "sight",
        coordinates: [33.2774, 131.4468],
        description: "搭乘纜車登上鶴見岳，俯瞰別府全景。",
        image: "",
    },
    {
        date: "2025-04-11",
        location: "別府塔 (Beppu Tower)",
        category: "sight",
        coordinates: [33.2808, 131.5103],
        description: "回到市區，從別府的地標上欣賞夜景。",
        image: "",
    },
    {
        date: "2025-04-11",
        location: "とよ常 (Toyotsune)",
        category: "food",
        coordinates: [33.2815, 131.502],
        description: "晚餐品嚐大分名物「とり天」雞肉天婦羅。",
        image: "",
    },
    {
        date: "2025-04-11",
        location: "杉乃井ホテル (Suginoi Hotel)",
        category: "stay",
        coordinates: [33.273, 131.4842],
        description: "入住別府知名的溫泉飯店，享受棚湯溫泉。",
        image: "",
    },
    {
        date: "2025-04-12",
        location: "湯布院花卉村 (Yufuin Floral Village)",
        category: "sight",
        coordinates: [33.2625, 131.3533],
        description: "充滿英式童話風格的可愛小鎮。",
        image: "",
    },
    {
        date: "2025-04-12",
        location: "湯之坪街道 (Yunotsubo Street)",
        category: "sight",
        coordinates: [33.2615, 131.356],
        description: "由布院最熱鬧的商店街，邊走邊逛。",
        image: "",
    },
    {
        date: "2025-04-12",
        location: "由布まぶし 心 (Yufumabushi Shin)",
        category: "food",
        coordinates: [33.2598, 131.3592],
        description: "午餐品嚐由布院必吃的豐後牛釜飯三吃。",
        image: "",
    },
    {
        date: "2025-04-12",
        location: "金鱗湖 (Lake Kinrin)",
        category: "sight",
        coordinates: [33.264, 131.3501],
        description: "由布院代表性的景點，湖光山色非常夢幻。",
        image: "",
    },
    {
        date: "2025-04-12",
        location: "COMICO ART MUSEUM YUFUIN",
        category: "sight",
        coordinates: [33.26, 131.3621],
        description: "由建築大師隈研吾設計的現代美術館。",
        image: "",
    },
    {
        date: "2025-04-12",
        location: "菅乃屋 上通店",
        category: "food",
        coordinates: [32.8055, 130.7108],
        description: "抵達熊本，晚餐品嚐道地的馬肉料理。",
        image: "",
    },
    {
        date: "2025-04-12",
        location: "Dormy Inn 熊本",
        category: "stay",
        coordinates: [32.804, 130.705],
        description: "今晚入住熊本市中心的飯店。",
        image: "",
    },
    {
        date: "2025-04-13",
        location: "熊本城 (Kumamoto Castle)",
        category: "sight",
        coordinates: [32.8068, 130.706],
        description: "參觀日本三大名城之一，感受其雄偉壯闊。",
        image: "",
    },
    {
        date: "2025-04-13",
        location: "桜の馬場 城彩苑 (Josaien)",
        category: "sight",
        coordinates: [32.8033, 130.7053],
        description: "體驗城下町的復古風情與美食。",
        image: "",
    },
    {
        date: "2025-04-13",
        location: "黒亭 (Kokutei)",
        category: "food",
        coordinates: [32.7958, 130.7011],
        description: "午餐品嚐加入焦蒜油的道地熊本拉麵。",
        image: "",
    },
    {
        date: "2025-04-13",
        location: "水前寺成趣園 (Suizenji Jojuen Garden)",
        category: "sight",
        coordinates: [32.7941, 130.7335],
        description: "精緻的日式迴遊式庭園，景色優美。",
        image: "",
    },
    {
        date: "2025-04-13",
        location: "熊本市現代美術館",
        category: "sight",
        coordinates: [32.8035, 130.7118],
        description: "欣賞現代藝術作品，感受城市的藝文氣息。",
        image: "",
    },
    {
        date: "2025-04-13",
        location: "ひょうたん寿司 (Hyotan Sushi)",
        category: "food",
        coordinates: [33.59, 130.398],
        description: "返回福岡，晚餐享用高人氣的壽司店。",
        image: "",
    },
    {
        date: "2025-04-13",
        location: "福岡日航飯店 (Hotel Nikko Fukuoka)",
        category: "stay",
        coordinates: [33.5905, 130.4208],
        description: "回到福岡，為明日的歸途做準備。",
        image: "",
    },
    {
        date: "2025-04-14",
        location: "太宰府天滿宮",
        category: "sight",
        coordinates: [33.5165, 130.5352],
        description: "參拜學問之神，祈求智慧與順利。",
        image: "",
    },
    {
        date: "2025-04-14",
        location: "光明禪寺 (Komyozenji Temple)",
        category: "sight",
        coordinates: [33.516, 130.534],
        description: "欣賞寧靜優美的枯山水「一滴海之庭」。",
        image: "",
    },
    {
        date: "2025-04-14",
        location: "お食事処 鬼瓦そば",
        category: "food",
        coordinates: [33.5158, 130.5333],
        description: "午餐品嚐太宰府的特色瓦片蕎麥麵。",
        image: "",
    },
    {
        date: "2025-04-14",
        location: "福岡機場 (Fukuoka Airport)",
        category: "transport",
        coordinates: [33.5859, 130.4506],
        description: "滿載回憶，準備回家。",
        image: "",
    },
    {
        date: "2025-04-14",
        location: "Home, Sweet Home",
        category: "stay",
        coordinates: [25.033, 121.5654],
        description: "旅途結束！",
        image: "",
    },
];
