let locationsData = [
    {
        date: "2025-07-25",
        location: "Home, Sweet Home",
        category: "transport",
        coordinates: [25.0330, 121.5654],
        description: "從台北出發，前往沖繩！",
        image: "",
    },
    {
        date: "2025-07-25",
        location: "那霸機場 (Naha Airport, OKA)",
        category: "transport",
        coordinates: [26.2066, 127.6469],
        description: "抵達沖繩，領取租車，開始旅程。",
        image: "",
    },
    {
        date: "2025-07-25",
        location: "豬肉蛋飯糰 牧志市場總店",
        category: "food",
        coordinates: [26.2160, 127.6885],
        description: "午餐品嚐沖繩的靈魂美食，現點現做的美味飯糰。",
        image: "",
    },
    {
        date: "2025-07-25",
        location: "首里城公園 (Shurijo Castle Park)",
        category: "sight",
        coordinates: [26.2171, 127.7195],
        description: "參觀琉球王國的歷史中心，感受王國時代的氛圍。",
        image: "",
    },
    {
        date: "2025-07-25",
        location: "波上宮 (Naminoue Shrine)",
        category: "sight",
        coordinates: [26.2219, 127.6729],
        description: "建在懸崖上的獨特神社，祈求旅途平安。",
        image: "",
    },
    {
        date: "2025-07-25",
        location: "琉球的牛 那霸國際通店",
        category: "food",
        coordinates: [26.2154, 127.6843],
        description: "晚餐享用高品質的沖繩縣產和牛燒肉。",
        image: "",
    },
    {
        date: "2025-07-25",
        location: "國際通 (Kokusai Dori)",
        category: "sight",
        coordinates: [26.2158, 127.6854],
        description: "晚餐後在有「奇蹟的一英里」之稱的商店街散步。",
        image: "",
    },
    {
        date: "2025-07-25",
        location: "那霸國際通大和ROYNET飯店",
        category: "stay",
        coordinates: [26.2163, 127.6890],
        description: "今晚入住位於國際通旁的飯店，地點便利。",
        image: "",
    },
    {
        date: "2025-07-26",
        location: "那霸國際通大和ROYNET飯店",
        category: "stay",
        coordinates: [26.2163, 127.6890],
        description: "從飯店出發，驅車前往沖繩北部。",
        image: "",
    },
    {
        date: "2025-07-26",
        location: "美麗海水族館 (Okinawa Churaumi Aquarium)",
        category: "sight",
        coordinates: [26.6941, 127.8778],
        description: "欣賞「黑潮之海」水槽中震撼的鯨鯊與鬼蝠魟。",
        image: "",
    },
    {
        date: "2025-07-26",
        location: "Ocean Blue 餐廳 (水族館內)",
        category: "food",
        coordinates: [26.6945, 127.8775],
        description: "午餐在水族館內的景觀餐廳用餐。",
        image: "",
    },
    {
        date: "2025-07-26",
        location: "古宇利島 & 心形岩",
        category: "sight",
        coordinates: [26.7118, 128.0175],
        description: "跨越跨海大橋，前往有「戀之島」美稱的古宇利島。",
        image: "",
    },
    {
        date: "2025-07-26",
        location: "萬座毛 (Cape Manzamo)",
        category: "sight",
        coordinates: [26.5052, 127.8473],
        description: "欣賞形如象鼻的奇特斷崖與壯闊海景。",
        image: "",
    },
    {
        date: "2025-07-26",
        location: "元祖海葡萄 (Ganso Umi Budou)",
        category: "food",
        coordinates: [26.4632, 127.8346],
        description: "晚餐品嚐沖繩特產海葡萄蓋飯。",
        image: "",
    },
    {
        date: "2025-07-26",
        location: "美國村 (American Village)",
        category: "sight",
        coordinates: [26.3165, 127.7678],
        description: "充滿異國風情的購物娛樂區，夜晚燈光璀璨。",
        image: "",
    },
    {
        date: "2025-07-26",
        location: "那霸國際通大和ROYNET飯店",
        category: "stay",
        coordinates: [26.2163, 127.6890],
        description: "晚上開車返回那霸市區飯店休息。",
        image: "",
    },
    {
        date: "2025-07-27",
        location: "那霸國際通大和ROYNET飯店",
        category: "stay",
        coordinates: [26.2163, 127.6890],
        description: "在沖繩的最後一天，從飯店退房出發。",
        image: "",
    },
    {
        date: "2025-07-27",
        location: "知念岬公園 (Cape Chinen Park)",
        category: "sight",
        coordinates: [26.1661, 127.8284],
        description: "從高處眺望270度的太平洋無敵海景。",
        image: "",
    },
    {
        date: "2025-07-27",
        location: "沖繩世界文化王國・玉泉洞",
        category: "sight",
        coordinates: [26.1421, 127.7503],
        description: "探索壯觀的鐘乳石洞，並體驗琉球傳統文化。",
        image: "",
    },
    {
        date: "2025-07-27",
        location: "沖繩麵屋 YAGI (Okinawa Soba YAGI)",
        category: "food",
        coordinates: [26.1450, 127.7490],
        description: "午餐品嚐道地的沖繩麵。",
        image: "",
    },
    {
        date: "2025-07-27",
        location: "瀨長島 Umikaji Terrace",
        category: "sight",
        coordinates: [26.1770, 127.6590],
        description: "地中海風格的白色建築群，欣賞飛機起降。",
        image: "",
    },
    {
        date: "2025-07-27",
        location: "ASHIBINAA Outlet Mall",
        category: "sight",
        coordinates: [26.1689, 127.6610],
        description: "進行最後的購物衝刺。",
        image: "",
    },
    {
        date: "2025-07-27",
        location: "那霸機場 (Naha Airport, OKA)",
        category: "transport",
        coordinates: [26.2066, 127.6469],
        description: "還車後，準備搭機回家。",
        image: "",
    },
    {
        date: "2025-07-27",
        location: "Home, Sweet Home",
        category: "stay",
        coordinates: [25.0330, 121.5654],
        description: "旅途結束！",
        image: "",
    }
];