export default [
    // --------------------------------------------
    // Arbitrum
    // --------------------------------------------
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Arbitrum",
        coin: "USDC",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "compound-arbitrum-usdc",
        source: "https://app.beefy.com/vault/compound-arbitrum-usdc",
        favorite: 0,
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Arbitrum",
        coin: "USDT",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "compound-arbitrum-usdt",
        source: "https://app.beefy.com/vault/compound-arbitrum-usdt",
    },
    {
        enabled: 0,
        platform: "Beefy Finance",
        chain: "Arbitrum",
        coin: "USDC",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "stargate-v2-arb-usdc",
        source: "https://app.beefy.com/vault/stargate-v2-arb-usdc",
    },
    {
        enabled: 0,
        platform: "Beefy Finance",
        chain: "Arbitrum",
        coin: "USDT",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "stargate-v2-arb-usdt",
        source: "https://app.beefy.com/vault/stargate-v2-arb-usdt",
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Arbitrum",
        coin: "USDC",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "venus-arb-usdc",
        source: "https://app.beefy.com/vault/venus-arb-usdc",
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Arbitrum",
        coin: "USDT",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "venus-arb-usdt",
        source: "https://app.beefy.com/vault/venus-arb-usdt",
    },
    // --------------------------------------------
    // Ethereum
    // --------------------------------------------
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Ethereum",
        coin: "USDC",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "compound-mainnet-usdc",
        source: "https://app.beefy.com/vault/compound-mainnet-usdc",
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Ethereum",
        coin: "USDC",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "morpho-smokehouse-usdc",
        source: "https://app.beefy.com/vault/morpho-smokehouse-usdc",
        favorite: 0,
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Ethereum",
        coin: "USDC",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "morpho-steakhouse-usdc",
        source: "https://app.beefy.com/vault/morpho-steakhouse-usdc",
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Ethereum",
        coin: "USDS",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "sky-usds",
        source: "https://app.beefy.com/vault/sky-usds",
    },
    // --------------------------------------------
    // Polygon
    // --------------------------------------------
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Polygon",
        coin: "USDC",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "morpho-compound-usdc",
        source: "https://app.beefy.com/vault/morpho-compound-usdc",
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Polygon",
        coin: "USDT",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "morpho-compound-usdt",
        source: "https://app.beefy.com/vault/morpho-compound-usdt",
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Polygon",
        coin: "USDC.e",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "compound-polygon-usdc",
        source: "https://app.beefy.com/vault/compound-polygon-usdc",
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Polygon",
        coin: "USDT",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "compound-polygon-usdt",
        source: "https://app.beefy.com/vault/compound-polygon-usdt",
    },
    // --------------------------------------------
    // Base
    // --------------------------------------------
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Base",
        coin: "USDC",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "compound-base-usdc",
        source: "https://app.beefy.com/vault/compound-base-usdc",
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Base",
        coin: "USDC",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "morpho-seamless-usdc",
        source: "https://app.beefy.com/vault/morpho-seamless-usdc",
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Base",
        coin: "USDC",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "morpho-ionic-usdc",
        source: "https://app.beefy.com/vault/morpho-ionic-usdc",
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Base",
        coin: "eUSD",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "morpho-morpho-eusd",
        source: "https://app.beefy.com/vault/morpho-morpho-eusd",
    },
    // --------------------------------------------
    // Sonic
    // --------------------------------------------
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Sonic",
        coin: "USDC.e",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "aavev3-sonic-usdc.e",
        source: "https://app.beefy.com/vault/aavev3-sonic-usdc.e",
        favorite: 0,
    },
    {
        enabled: 1,
        platform: "Beefy Finance",
        chain: "Sonic",
        coin: "USDC.e",
        url: "https://api.beefy.finance/apy/breakdown",
        selector: "swapx-ichi-ws-usdc.e-usdc.e",
        source: "https://app.beefy.com/vault/swapx-ichi-ws-usdc.e-usdc.e",
        favorite: 1,
    },
];
